---
deployment:
  tasks:
    - export DEPLOYPATH=/home/yyrigitd/gemverify.com.ng/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R api $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R user $DEPLOYPATH
