/* Super-admin ZenithPay controls and reconciliation panel. */
(function(){
  const api='../api', token=()=>localStorage.getItem('gv_admin_token')||'';
  async function call(path, opts){ const r=await fetch(api+path,Object.assign({headers:{Authorization:'Bearer '+token()}},opts||{})); return r.json(); }
  function open(){
    let old=document.getElementById('gv-z-admin'); if(old){old.remove();return;}
    const el=document.createElement('div'); el.id='gv-z-admin'; el.style.cssText='position:fixed;inset:0;z-index:10000;background:rgba(0,0,0,.55);padding:24px;overflow:auto;font:14px system-ui';
    el.innerHTML='<div style="max-width:860px;margin:auto;background:#fff;color:#102044;border-radius:16px;padding:22px"><button id="z-close" style="float:right;border:0;background:none;font-size:22px">×</button><h2 style="margin:0 0 16px">ZenithPay Funding</h2><div id="z-settings">Loading settings…</div><h3>Recent deposits</h3><div id="z-deposits">Loading deposits…</div><h3>Recover account after provider timeout</h3><form id="z-recover" style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px"><input name="user_id" placeholder="User ID" required><input name="account_reference" placeholder="Account reference" required><input name="account_number" placeholder="Account number" required><input name="account_name" placeholder="Account name" required><input name="bank_name" placeholder="Bank name" required><button style="grid-column:span 2;padding:10px;background:#2563eb;color:white;border:0;border-radius:8px">Save recovered account</button></form><p id="z-msg"></p></div>';
    document.body.appendChild(el); el.querySelector('#z-close').onclick=()=>el.remove();
    Promise.all([call('/admin/payment-gateways'),call('/admin/zenithpay/deposits?limit=20'),call('/admin/payment-providers')]).then(([settings,deposits,providers])=>{
      const values=Object.fromEntries((settings.data?.settings||[]).map(x=>[x.setting_key,x.setting_value==='1']));
      el.querySelector('#z-settings').innerHTML='<label><input id="z-kat" type="checkbox" '+(values.katpay_funding_enabled?'checked':'')+'> KatPay funding enabled</label><br><label><input id="z-act" type="checkbox" '+(values.zenithpay_activation_enabled?'checked':'')+'> ZenithPay activation enabled</label><button id="z-save" style="margin:10px;padding:7px 12px">Save settings</button>';
      el.querySelector('#z-save').onclick=async()=>{let j=await call('/admin/payment-gateways',{method:'PATCH',headers:{Authorization:'Bearer '+token(),'Content-Type':'application/json'},body:JSON.stringify({katpay_funding_enabled:el.querySelector('#z-kat').checked,zenithpay_activation_enabled:el.querySelector('#z-act').checked})}); el.querySelector('#z-msg').textContent=j.message||'Saved';};
      const providerRows=(providers.data?.providers||[]).map(p=>'<div data-provider="'+p.provider_key+'" style="margin:8px 0;padding:8px;border:1px solid #dbe3f0;border-radius:8px"><b>'+p.display_name+'</b> <label><input class="z-visible" type="checkbox" '+(parseInt(p.customer_funding_enabled)?'checked':'')+'> Customer visible</label> <label><input class="z-maintenance" type="checkbox" '+(parseInt(p.maintenance_enabled)?'checked':'')+'> Maintenance</label> <button class="z-provider-save">Save</button></div>').join('');
      const providersBox=document.createElement('div');providersBox.innerHTML='<h3>Customer funding providers</h3>'+providerRows;el.querySelector('#z-settings').appendChild(providersBox);
      providersBox.querySelectorAll('[data-provider]').forEach(row=>row.querySelector('.z-provider-save').onclick=async()=>{const p=row.dataset.provider;const body={customer_funding_enabled:row.querySelector('.z-visible').checked,maintenance_enabled:row.querySelector('.z-maintenance').checked,account_assignment_enabled:p==='zenithpay',display_order:p==='zenithpay'?10:20};const j=await call('/admin/payment-providers/'+encodeURIComponent(p),{method:'PATCH',headers:{Authorization:'Bearer '+token(),'Content-Type':'application/json'},body:JSON.stringify(body)});el.querySelector('#z-msg').textContent=j.message||'Saved';});
      const rows=deposits.data?.data||[]; el.querySelector('#z-deposits').innerHTML=rows.length?'<table style="width:100%;border-collapse:collapse"><tr><th>Transaction</th><th>User</th><th>Paid</th><th>Settlement</th><th>Status</th></tr>'+rows.map(d=>'<tr><td>'+d.transaction_id+'</td><td>'+(d.business_name||'Unmatched')+'</td><td>₦'+d.gross_amount+'</td><td>₦'+(d.settlement_amount||'—')+'</td><td>'+d.processing_status+'</td></tr>').join('')+'</table>':'No ZenithPay deposits yet.';
    }).catch(()=>{el.querySelector('#z-settings').textContent='Unable to load ZenithPay controls.';});
    el.querySelector('#z-recover').onsubmit=async(e)=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));let j=await call('/admin/zenithpay/accounts/recover',{method:'POST',headers:{Authorization:'Bearer '+token(),'Content-Type':'application/json'},body:JSON.stringify(d)});el.querySelector('#z-msg').textContent=j.message||'Saved';};
  }
  window.addEventListener('load',()=>{if(!token())return;const b=document.createElement('button');b.textContent='ZenithPay';b.style.cssText='position:fixed;right:18px;bottom:18px;z-index:9999;padding:10px 14px;border:0;border-radius:20px;background:#0f4cdb;color:white;font-weight:700';b.onclick=open;document.body.appendChild(b);});
})();
